// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN9mND2-f_dnD6sumQ43YKwBsD44GVpBU',
    appId: '1:357320241600:web:ca8fbbeb9104354f22d825',
    messagingSenderId: '357320241600',
    projectId: 'sriram-4c02b',
    authDomain: 'sriram-4c02b.firebaseapp.com',
    storageBucket: 'sriram-4c02b.firebasestorage.app',
    measurementId: 'G-719L3XSX4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjNRzABIXFS2O-CA8OsNy8fpYop453smo',
    appId: '1:357320241600:android:d46de190311e799b22d825',
    messagingSenderId: '357320241600',
    projectId: 'sriram-4c02b',
    storageBucket: 'sriram-4c02b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx82Ow1fSwKVn9YGNUdQGMbGvELev80R0',
    appId: '1:357320241600:ios:bc25d06cddc381c722d825',
    messagingSenderId: '357320241600',
    projectId: 'sriram-4c02b',
    storageBucket: 'sriram-4c02b.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
